services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer
    ports:
      - '8080:8080'
    environment:
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - USED_ITEMS=${USED_ITEMS}
      - MATCH_RESULTS=${MATCH_RESULTS}
      